name: PyDnD Tests

on:
  push:
    branches: 
      - main
      - development
  pull_request:
    branches: 
      - main
      - development

jobs:
  build:

    runs-on: ubuntu-18.04  # Using an older Ubuntu version for Python 3.6 support

    strategy:
      matrix:
        python-version: [3.6.15, 3.8, 3.9, 3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run tests
      run: |
        python -m unittest discover -s tests
